name: onctest1
channels:
- defaults
dependencies:
- ca-certificates=2019.1.23
- certifi=2019.3.9=py36_0
- libedit=3.1.20181209
- libffi=3.2.1
- ncurses=6.1
- openssl=1.1.1b
- pip=9.0.3=py36_0
- python=3.6.8
- readline=7.0
- setuptools=40.8.0=py36_0
- sqlite=3.27.2
- tk=8.6.8
- wheel=0.33.1=py36_0
- xz=5.2.4
- zlib=1.2.11
- pip:
  - docutils==0.14
  - geoparse==1.0.5
  - jmespath==0.9.3
  - lifelines==0.14.0
  - pyasn1==0.4.2
  - wgetter==0.7

